inherit_from:
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml
  - .rubocop_todo.yml

# We're OK with a class of EveryPolitician
Style/ConstantName:
  Exclude:
    - 'lib/everypolitician.rb'
