inherit_from:
  - https://raw.githubusercontent.com/everypolitician/everypolitician-data/master/.rubocop_base.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.3

Style/SafeNavigation:
  Enabled: false
